# ============================================================
#  Makefile — danish-texts
#
#  Builds PDFs from all .tex source files in texts/.
#  After building, run sync-pdfs.sh to push PDFs to phi423.
#
#  Usage:
#    make              rebuild all out-of-date PDFs
#    make all          same as above
#    make clean        remove LaTeX auxiliary files (keep PDFs)
#    make cleanall     remove auxiliary files and compiled PDFs
#    make list         list all .tex sources and their PDF status
#    make help         show this message
#    make -j4          parallel build with 4 jobs
# ============================================================

# Discover all .tex sources and derive PDF targets.
# Excludes .parts/ — transcription batches that are still fragments are staged there
# before being spliced into the main document. A fragment has no preamble and no
# \begin{document}, so trying to build it standalone fails with "Missing \begin{document}".
# Fragments also carry a .texfrag extension for the same reason; this is belt and braces.
TEXFILES := $(shell find texts -name '*.tex' -not -path '*/.parts/*' | sort)
PDFFILES  := $(TEXFILES:.tex=.pdf)

# latexmk flags: pdf mode, non-interactive, stop on first error
LATEXMK   := latexmk -pdf -interaction=nonstopmode -halt-on-error
LATEXMKLUA := latexmk -lualatex -interaction=nonstopmode -halt-on-error

.PHONY: all clean cleanall list help dossiers private

all: $(PDFFILES)

# LuaLaTeX overrides for files using fontspec/unicode-math
# (must come before the general pattern rule)
texts/hoeffding/relation-som-kategori/transcription.pdf: \
  texts/hoeffding/relation-som-kategori/transcription.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

texts/hoeffding/relation-som-kategori/translation.pdf: \
  texts/hoeffding/relation-som-kategori/translation.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

texts/hoeffding/personlighedsprincippet/translation.pdf: \
  texts/hoeffding/personlighedsprincippet/translation.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

# Brøchner, Bidrag til Opfattelsen af Philosophiens historiske Udvikling (1869).
# LuaLaTeX, not pdfLaTeX, and deliberately: the book carries 400--600 words of
# polytonic Greek. Under pdfLaTeX the Greek goes through LGR, for which
# Libertinus has no Type1 face, so it falls back to CB Greek -- a Computer
# Modern Greek that clashes with the Libertinus text and sets upright, where
# the book's Greek fount is a cursive. Under LuaLaTeX the Greek comes from
# Libertinus Serif itself, with the iota subscript the book needs (ἐνεργείᾳ,
# p. 99 and the errata leaf). Reasoning is repeated in the file's own header §6.
texts/brochner/philosophiens-udvikling/transcription.pdf: \
  texts/brochner/philosophiens-udvikling/transcription.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

# Brøchner, Philosophiens Historie i Grundrids, 1. and 2. Deel (1873--74).
# LuaLaTeX for the same reason as the 1869 Bidrag above, and more so: 1. Deel
# alone carries 8194 Greek characters on 163 of its 274 pages, including the
# variant sorts and the iota subscript. Both parts load fontspec, so the
# generic pdfLaTeX rule below cannot build them at all -- it dies at
# fontspec's "cannot-use-pdftex".
texts/brochner/philosophiens-historie-1/transcription.pdf: \
  texts/brochner/philosophiens-historie-1/transcription.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

texts/brochner/philosophiens-historie-2/transcription.pdf: \
  texts/brochner/philosophiens-historie-2/transcription.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

# Cross-author source dossiers (texts/dossiers/README.md). Two steps:
#   selection.txt (+ intro.texfrag) --dossier.py--> dossier.tex --lualatex--> dossier.pdf
# dossier.tex is GENERATED: edit selection.txt or intro.texfrag, and `make`
# regenerates it. Generating needs ~/sks-search and its index (see the README).
# Pattern rules, so every future texts/dossiers/<word>/ is covered; they must
# stay above the general %.pdf rule, because make 3.81 (macOS) picks the first
# matching pattern rule rather than the most specific one. LuaLaTeX because
# the dossier loads fontspec and sets Greek and Hebrew.
# A dossier with its own build.py (the Bohr one, texts/dossiers/entydig/) is
# generated by that script instead; this rule comes first, and make falls
# through to the selection.txt rule for a directory that has no build.py.
texts/dossiers/%/dossier.tex: texts/dossiers/%/build.py texts/dossiers/%/printed.yaml $(wildcard texts/dossiers/*/intro.texfrag)
	cd $(dir $@) && python3 build.py

texts/dossiers/%/dossier.tex: texts/dossiers/%/selection.txt dossier.py $(wildcard texts/dossiers/*/intro.texfrag)
	python3 dossier.py $(dir $@)

texts/dossiers/%/dossier.pdf: texts/dossiers/%/dossier.tex
	cd $(dir $<) && $(LATEXMKLUA) $(notdir $<)

# Private copies of the dossiers, kept outside this repo in ~/research: they
# include what the public ones must leave out (in-copyright e-book passages;
# Bohr's aligned originals whole). publish-danish.sh builds them on every run,
# and each is rebuilt only when its sources change. Nothing here is committed.
PRIVATE := $(HOME)/research
TILEGN  := texts/dossiers/tilegnelse
ENTYD   := texts/dossiers/entydig
PRIVATE_PDFS := $(PRIVATE)/tilegnelse-dossier/tilegnelse-udvalg.pdf \
                $(PRIVATE)/tilegnelse-dossier/tilegnelse-dossier.pdf \
                $(PRIVATE)/entydig-dossier/dossier.pdf
XELATEX := xelatex -interaction=nonstopmode

private: $(PRIVATE_PDFS)

$(PRIVATE)/tilegnelse-dossier/tilegnelse-udvalg.pdf: $(TILEGN)/selection.txt dossier.py $(wildcard $(TILEGN)/intro.texfrag)
	mkdir -p $(dir $@)
	python3 dossier.py $(TILEGN) --ebooks -o $(basename $@).tex
	cd $(dir $@) && $(XELATEX) $(notdir $(basename $@)).tex >/dev/null && $(XELATEX) $(notdir $(basename $@)).tex >/dev/null

$(PRIVATE)/tilegnelse-dossier/tilegnelse-dossier.pdf: dossier.py
	mkdir -p $(dir $@)
	python3 dossier.py 'tilegn*' --authors sibbern,kierkegaard,brochner,hoeffding --title Tilegnelse --ebooks -o $(basename $@).tex
	cd $(dir $@) && $(XELATEX) $(notdir $(basename $@)).tex >/dev/null && $(XELATEX) $(notdir $(basename $@)).tex >/dev/null

$(PRIVATE)/entydig-dossier/dossier.pdf: $(ENTYD)/build.py $(ENTYD)/printed.yaml $(wildcard $(ENTYD)/intro.texfrag)
	mkdir -p $(dir $@)
	python3 $(ENTYD)/build.py --private -o $(basename $@).tex
	cd $(dir $@) && $(XELATEX) dossier.tex >/dev/null && $(XELATEX) dossier.tex >/dev/null

# Regenerate every dossier even if its selection is unchanged -- after a
# transcription has been corrected and sks-search re-indexed, say.
dossiers:
	for d in texts/dossiers/*/; do \
	  if [ -f $$d/build.py ]; then (cd $$d && python3 build.py) || exit 1; \
	  else python3 dossier.py $$d || exit 1; fi; done

# Compile each .tex to PDF.
# cd into the source directory first so relative paths resolve correctly.
# latexmk detects how many pdflatex passes are needed (typically 2 for
# files with a table of contents or cross-references).
%.pdf: %.tex
	cd $(dir $<) && $(LATEXMK) $(notdir $<)

# Remove LaTeX auxiliary files, leaving PDFs intact.
clean:
	@find texts \( \
	  -name '*.aux'            \
	  -o -name '*.fdb_latexmk' \
	  -o -name '*.fls'         \
	  -o -name '*.log'         \
	  -o -name '*.out'         \
	  -o -name '*.synctex.gz'  \
	  -o -name '*.toc'         \
	  -o -name '*.xdv'         \
	\) -delete
	@echo "Auxiliary files removed."

# Remove auxiliary files and all locally-compiled PDFs.
# Does not touch PDFs that have no .tex source (sync-pdfs.sh handles those).
cleanall: clean
	@rm -f $(PDFFILES)
	@echo "Auxiliary files and compiled PDFs removed."

# Show each .tex source and whether its PDF is up to date.
list:
	@echo ""
	@echo "Source files and PDF status:"
	@echo "-----------------------------"
	@for tex in $(TEXFILES); do \
	  pdf=$${tex%.tex}.pdf; \
	  if [ ! -f "$$pdf" ]; then \
	    echo "  MISSING  $$tex"; \
	  elif [ "$$tex" -nt "$$pdf" ]; then \
	    echo "  STALE    $$tex"; \
	  else \
	    echo "  ok       $$tex"; \
	  fi; \
	done
	@echo ""

help:
	@echo ""
	@echo "  make           rebuild all out-of-date PDFs"
	@echo "  make clean     remove LaTeX auxiliary files"
	@echo "  make cleanall  remove auxiliary files and compiled PDFs"
	@echo "  make list      show PDF status for each source file"
	@echo "  make -j4       parallel build with 4 jobs"
	@echo "  make dossiers  regenerate every texts/dossiers/*/dossier.tex (see texts/dossiers/README.md)"
	@echo ""
	@echo "  After building, run 'bash sync-pdfs.sh' to push PDFs to phi423."
	@echo ""
